### ISSUE TITLE
Subscribe to topics on first startup

### ISSUE THREAD

**Issue by HarveyBates** [HarveyBates/Phenobottle#5]
Need to subscribe to all basic MQTT topics on setup. The best way to do this (I think) is by using a shell script as I can start by:

1. Installing dependancies (mosquitto etc.)
2. Creating unique user id (16 digit random number letter sequence) and adding user credentials to MQTT-Broker / Database
3. Subscribe the current user to all basic topics

The topics will be formatted as (baseline list):
{user_id}/{phenobottle_treatment}/sensor/temperature
{user_id}/{phenobottle_treatment}/sensor/optical_density
{user_id}/{phenobottle_treatment}/sensor/fluorescence/parameters
{user_id}/{phenobottle_treatment}/sensor/fluorescence/raw
{user_id}/{phenobottle_treatment}/motor/mixing
{user_id}/{phenobottle_treatment}/motor/media_in
{user_id}/{phenobottle_treatment}/motor/culture_out
{user_id}/{phenobottle_treatment}/lights
{user_id}/{phenobottle_treatment}/temperature/motor
{user_id}/{phenobottle_treatment}/temperature/fan
{user_id}/{phenobottle_treatment}/temperature/peristaltic

*phenobottle_treatment* is defined by the user in JS.

**The issue with this is that the wildcard ```#``` can be used in replacement of {user_id} and/or {phenobottle_treatment} allowing anyone to see the published messages.**

**Comment by CamDavidsonPilon** [comment]
Hey @HarveyBates, I hope you don't mind me jumping in with some comments! Cool to see you using MQTT. I'm still a big fan, but my implementation of it has evolved for Pioreactor, so I can share what I've learned (some of which you may already know):

1. MQTT natively doesn't have timestamps of when messages are created / published, but this is often important for downstream processes (storing in a DB, visualizing on a UI, etc.). I've moved mostly away from sending _floats_ as message payloads, to sending a json string of float-value and timestamps, ex: `{"temperature": 40, "timestamp": "2021-06-21T14:40:36Z"}`. Yes, there is more code, more serializing & unpacking, and more work done by the broker's CPU, but it's worth it. If a connection is lost between client + broker, even for a few seconds, not having a timestamp will create data problems. Also, using a json string allows for other metadata to be passed around.
2. I loosely follow the [Homie convention](https://homieiot.github.io/specification/):
   - their lifecycle section is useful to think about, including variables like`$state` (7.1.2)
   - their `set` topic syntax is nice (7.3.2)
 Keep in mind that the Homie convention is only a guide, and break it (consistently) when you want. 
3. The Python implementation of the client, `paho`, works really well, but has some quirks. For example, you can't publish in a callback. That took me a long time to figure out haha.
4. On the JS side, I found lots of performance improvements when I was able to reuse clients between subscriptions, instead of creating a client for each subscription. 
5. ` mosquitto_sub -v -t "#" -F "%I %t %p"` to show timestamps with the log
6. Almost always, when I've used MQTT as a "database", I've been bitten with a difficult bug / problem later. For example, I keep the state of my LEDs intensity in MQTT, something like `{"A": 50, "B": 0, "C"0}`, and when I update an LED, I subscribe to this topic, unserialize, update json, serialize, and publish back. This sounds fine, but fails down the line: 
   - no guaranteed persistance on disk
   - no way to handle race conditions, eg: multiple ppl trying to update
   - no way to recover if wiped by mistake. 
 
 A proper database does all this, by design. My point is: treat keeping important state _only_ in MQTT as an anti-pattern, i.e. don't turn MQTT into a database. 

Your note: "The issue with this is that the wildcard #..."  is correct, but if the user has the password/username, then they should be _allowed_ to see the entire tree of topics. I think the security should be at the level of username/password - i.e. that pair should only be given to trusted ppl. If multiple parties are using the same broker (the googlable word is "multi-tenant"), you'll need to design the broker to handle that at start up.

**Comment by HarveyBates** [comment]
Hey @CamDavidsonPilon 
Thanks for all the information! Yea it took me a while to come around to MQTT, I recently got a job working on LoRaWAN sensors for agriculture which communicate over MQTT. 

I was checking out your Pioreactor code base this weekend, its clear that you have put in a lot of work, I hope the system is working well for you. Keen for the day I can buy one!

1. That is a really smart idea! Worth it for the timestamps
2. Really good to know about the homie convention, I'm going to have a play around with it this weekend
3. That is good to know, I am tossing up if I should write the client code in C++ but i don't know if it will have the same issue
4. Ok ill look into that some more
5. Thank you!!
6. Yea I think I would have approached it in the same way. In the past when i was using my C++ websockets I formatted my LED packets as strings (**LR&I:50&F:20000**)  which converts to: **Light Color: Red, Intensity: 50 bits, Frequency: 20 kHz**. However, I was counting on my microcontroller to handle that which might be super slow. I'm worried about the race conditions now. Ideally I want the user to either be able to setup an experiment dynamically in JS or just upload a .yaml file if systems fail.
7. haha that would have been rough, I'll keep that in mind

Yea the plan is to have a seperate postgresql database to handle things in regards to data storage. 

I want to manage the MQTT broker for multiple parties so I am going to have to look further into the future. I'll look some more into multi tenants! 

Thank you!
